---
title: "`twol`, транслитерация"
author: "Г. Мороз, Н. Хауэлл"
date: "16 декабря 2021"
output: 
  html_document:
    toc: true
    toc_position: right
    toc_depth: 2
    toc_float: yes
    number_sections: true
    df_print: paged
    keep_md: true
---

```{r setup, include=FALSE}
library('knitr')
knit_hooks$set(prompt = function(before, options, envir) {options(prompt = "$ ")})
opts_chunk$set(comment = "", prompt = TRUE)
```

```{bash, include=FALSE}
make clean
```

# Наши встречи

| дата       | тема                                   | материалы                                                                                  | видео                                 |
|------------|----------------------------------------|--------------------------------------------------------------------------------------------|---------------------------------------|
| 2021.11.08 | нахско-дагестанские языки, linux, lexd |                                                                                            | [видео](https://youtu.be/oslfxrYjt_A) |
| 2021.12.02 | linux, lexd, github, makefiles         | [материалы](https://agricolamz.github.io/2021.12.02_intro_to_linux_lexd_github_makefiles/) | [видео](https://youtu.be/3ULre3nuIhU) |
| 2021.12.09 | gitignore, tests, githooks             | [материалы](https://agricolamz.github.io/2021.12.09_gitignore_tests_githooks/)             | [видео](https://youtu.be/8v6ajrlOGuA) |
| 2021.12.16 | `twol`, транслитерация видео           | [материалы](https://agricolamz.github.io/2021.12.16_twol_transliteration/)                 |                                       |

# `twol`[^1]

[^1]: Весь этот раздел я бездумно списал из прошлогодних материалов Ника Хауэлла. Я старался списывать только то, что я понял...

`twol` --- это 

* формализм для описания морфонологии;
* язык программирования для описания морфонологических правил;
* `twolc` --- компилятор этого языка.

`twol` состоит из 

* 'алфавита' --- список возможных трансформаций;
* 'правила' --- список двухуровневых правил.

Важно понимать, что фонологические правила в `twol` не правила в стиле генеративной фонологии. Правила в `twol` не упорядочены, а применяются все сразу.

## Первый пример

В андийском есть коммитатив -лой, который ассимилируется, если основа заканчивается на *н*. Вот мой `and.lexd`:

```{bash, echo = FALSE}
cat and.lexd
```


Я хочу написать, правило `л -> н / н _`. Так как это правило должно применяться не всегда, а только в показателе коммитатива, я ввожу специальную абстракцию `{л}` (ее принято называть *архифонемой*, но лучше не думать над лингвистическим употреблением этого термина), реализацию которой я пропишу в правилах `and.twol`.

```{bash, echo = FALSE}
cat and.twol
```

Теперь можно сделать из этого файла трансдьюcер:

```{bash}
hfst-twolc and.twol -o and.twol.hfst
```

На него нельзя поглядеть при помощи `hfst-fst2strings`, потому что он зациклен. Теперь нужно сделать трансдьюсер из файла `.lexd`:

```{bash}
lexd and.lexd | hfst-txt2fst -o and.lexd.hfst
```

Давайте поглядим на результат:
```{bash}
hfst-fst2strings and.lexd.hfst
```

Теперь давайте соединим наши трансдьюсеры и посмотрим, что получилось:
```{bash}
hfst-compose-intersect and.lexd.hfst and.twol.hfst -o and.generator.hfst
```

```{bash}
hfst-fst2strings and.generator.hfst
```

## Изменения в морфотактике, или элизия в `twol`[^2]

[^2]: Ник в последний момент пришел и помог с этой частью. Ура!

С прошлого раза у нас осталась проблема, заключающаяся в том, что в формах элатива оставался тэг эссива:

```
берка<n><obl><super><essive><elative>:беркуъакку
берка<n><obl><sub><essive><elative>:беркулIикку
```

Хотелось бы тег `<essive>` удалить. Это тоже можно решить при помощи отдельного `.twol` файла, который будет разбираться с морфотактикой (файл называется `and.morphotactics.twol`):

```{bash, echo = FALSE}
cat and.morphotactics.twol
```

Мы его тоже можем скомпилировать в трансдьюсер 

```{bash}
hfst-twolc and.morphotactics.twol -o and.morphotactics.twol.hfst
```
```{bash}
hfst-invert and.lexd.hfst | hfst-compose-intersect - and.morphotactics.twol.hfst | hfst-invert -o and.morphotactics.hfst
```
```{bash}
hfst-compose-intersect and.morphotactics.hfst and.twol.hfst -o and.generator.hfst
```
```{bash}
hfst-fst2strings and.generator.hfst
```

## `Makefile`

Все пройденное можно соединить в одном `Makefile`:

```{bash}
sed -n -e 1,16p -e 31,39p Makefile
```

# Транслитерация

Как и в любой правиловой транслитерации нам нужен файл соответствий (`correspondence`):

```{bash, echo = FALSE}
cat correspondence
```

Мы его можем превратить в трансдьюссер `correspondence.hfst`:

```{bash}
hfst-strings2fst -j correspondence -o correspondence.hfst
```

Пока мы можем его посмотреть, но он не отличается от нашего файла:

```{bash}
hfst-fst2strings correspondence.hfst
```

Мы можем даже его применить, но только к символам из нашей таблицы соответствий:

```{bash}
echo "b" | hfst-lookup correspondence.hfst
```

```{bash}
echo "tɬ" | hfst-lookup correspondence.hfst
```

Т. е. текст он пока не транслитерирует:
```{bash}
echo "berka" | hfst-lookup correspondence.hfst
```

Чтобы построить транслитератор, нам нужно, чтобы наш трансдьюсер, применяя список соответствий, зациклился:

```{bash}
hfst-repeat -f 1 correspondence.hfst -o la2cy.transliterater.hfst
```

Теперь мы построили транслитератор `la2cy.transliterater.hfst`:

```{bash}
echo "berkutɬi" | hfst-lookup la2cy.transliterater.hfst
```

## Объединение с морфологическими анализаторами

Как и в случае с парой анализатор-генератор, мы можем инвертировать наш транслитератор, чтобы получить транслитератор, который транслитерирует из кириллицы в латиницу:

```{bash}
hfst-invert la2cy.transliterater.hfst -o cy2la.transliterater.hfst
```

```{bash}
echo "беркулIи" | hfst-lookup cy2la.transliterater.hfst
```

Если в прошлые разы мы строили морфологические анализаторы, которые работали с кириллицей, то теперь мы можем соединить их с нашими транслитераторами:

```{bash, include = FALSE}
make
```

```{bash}
hfst-compose and.generator.hfst cy2la.transliterater.hfst -o and.generator.tr.hfst
```

Что получилось:
```{bash}
hfst-fst2strings and.generator.tr.hfst
```

Можем перевернуть и сделать анализатор:

```{bash}
hfst-invert and.generator.tr.hfst -o and.analizer.tr.hfst
```

Результат:
```{bash}
hfst-fst2strings and.analizer.tr.hfst
```

Теперь можно суммировать все изученное в одном `Makefile`:

```{bash, echo = FALSE}
cat Makefile
```

## Сложности

Пока мне придумалось лишь несколько сложностей (вполне преодолимых, как мне кажется):

* при введение инородного символа все ломается (хотелось бы, чтобы появлялся какой-то символ обозначающий поломку):

```{bash}
echo "бяркулIи" | hfst-lookup cy2la.transliterater.hfst
```

* case sensitivity

```{bash}
echo "БЕркулIи" | hfst-lookup cy2la.transliterater.hfst
```

* перегенерация

```
берка<n><obl><sub><essive><elative>:berkutɬikku
берка<n><obl><sub><essive><elative>:berkutɬikːu
```

* учет контекста

В некоторых орфографиях графема обозначает одно в одном контексте и другое в другом (например /ё/ в ***ё**ж* и *Л**ё**ва*). Хотелось бы, чтобы этот контест можно было бы прописывать без использования `twolc` :)